### PR TITLE
chore(): Update oazapfts version to v4.3.3 (latest), enabling enum using a flag --useEnumType

### PR DESCRIPTION
**Pull request by boazhoch**
Update oazapfts version to v4.3.3 (latest), enabling enum using a flag --useEnumType

### CODE REVIEW

**Comment by boazhoch** [comment]
@kahirokunn @msutkowski Please have a look at this.
I have updated `oazapfts` to latest tag v4.3.3, this enables using a `useEnumType` flag.

And might help resolve this issue: [#1889](https://github.com/reduxjs/redux-toolkit/issues/1889)

**Review by kahirokunn — APPROVED** [review]
LGTM

**Comment by boazhoch** [comment]
Done

**Review by boazhoch — COMMENTED** [review]
Done

**Comment by boazhoch** [comment]
> LGTM

Can you merge it?

**Comment by kahirokunn** [comment]
I have no authority.

**Comment by boazhoch** [comment]
@msutkowski Please review PR.

**Comment by na0x2c6** [comment]
@boazhoch  
Thank you for your great work.
You may need assign @msutkowski as Reviewers or Assignees to notify him of your work.

**Pull request closed without merging**
